spring:
  application:
    name: cc-order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml
  datasource:
    url: jdbc:mysql://localhost:3306/ccorder?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost
    port: 6379

server:
  port: 8083

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cc.order.model

logging:
  level:
    com.cc.order: debug